Occupancy: 0

Excluded_taxa:
  Amerizus_cf_gosainkundensis
  Sinechostictus_lederi
  Anillini_Oregon
  Merizodus_sp_Valdivia
  Bembidion_sp_nr_nahuala
  Caecidium_trechomorphum
  Bembidion_eurydice_clarum
  Orzolina
  Tasmanitachoides_wilsoni
  Patrobus_longicornis
  Tachyura_obesulus
  Trechus_obtusus
  Pogonus_chalceus
  Pterocyrtus_rubescens
  Phrypeus_rickseckeri